Might as well exit with error code if lint apply commands fail too

diff --git a/lint b/lint
--- a/lint
+++ b/lint
@@ -2,18 +2,22 @@
 
 set -xo pipefail
 
+# exit mode is off in order to run all commands and report all errors
+# but we still want to exit with error if any of the commands fail
+had_error=0
+
 if [[ "$1" == "apply" ]]; then
     # Uses each linter's option to apply the changes if it is supported
-    black clinvar_ingest test
-    isort clinvar_ingest test
-    ruff --fix clinvar_ingest test
-    pylint --disable=C,R,W clinvar_ingest
+    black clinvar_ingest test || had_error=1
+    isort clinvar_ingest test || had_error=1
+    ruff --fix clinvar_ingest test || had_error=1
+    pylint --disable=C,R,W clinvar_ingest || had_error=1
 else
     # Check-only mode
-    had_error=0
     black --check clinvar_ingest test || had_error=1
     isort --check-only clinvar_ingest test || had_error=1
     ruff check clinvar_ingest test || had_error=1
     pylint --disable=C,R,W clinvar_ingest || had_error=1
-    exit $had_error
 fi
+
+exit $had_error
